version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/filecoin-project/go-leb128
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: 
      	  name: Get
	  command: go get -v -t -d ./...
      - run: 
      	  name: Test
	  command: go test -v ./...
